name: App Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  app-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout your repository

      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE test;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot

      - name: Run docker commands
        run: |
          docker build -f ${{ github.workspace }}/Dockerfile -t test-app .
          docker run -p 80:80 -e DB_USER=root -e DB_PASSWORD=root -e DB_HOST=127.0.0.1 -e DB_NAME=test test-app
          sleep 5
          curl -s -o /dev/null -w "%{http_code}" http://localhost:80/health | grep -q 200
