name: App Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout your repository

      - name: Run docker commands
        run: |
          docker build -f ${{ github.workspace }}/Dockerfile -t test-app .
          docker run -p 5000:5000 test-app
          curl http://localhost:5000/health
