name: App Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  app-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout your repository

      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE test;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot

      - name: Wait for MySQL to Startup
        run: sleep 60

      - name: Docker Build
        run: docker build -f ${{ github.workspace }}/Dockerfile -t test-app .

      - name: Docker Run
        run: docker run -p 80:80 -e DB_USER=root -e DB_PASSWORD=root -e DB_HOST=127.0.0.1:3306 -e DB_NAME=test test-app

      - name: Wait for App Startup
        run: sleep 5
      
      - name: Test App
        run: curl -s -o /dev/null -w "%{http_code}" http://localhost:80/health | grep -q 200
