name: App Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  app-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout your repository

      - name: Docker Build
        run: docker build -f ${{ github.workspace }}/Dockerfile -t test-app .

      - name: Docker Run
        run: docker run -p 80:80 -e DB_USER=${{ secrets.DB_USER }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_HOST=${{ secrets.DB_HOST }} -e DB_NAME=project test-app &

      - name: Wait for App Startup
        run: sleep 5
      
      - name: Build and Test App
        run: curl -s -o /dev/null -w "%{http_code}" http://localhost:80/health | grep -q 200
